import { Activity, CalendarDays, ChevronRight, ClipboardList, Command, FileBarChart, HeartPulse, Menu, Settings2, UsersRound, Wifi, X } from 'lucide-react';
import { type ReactNode, useState } from 'react';
import { Link, useLocation } from 'wouter';
import { getHealthCheckQueryKey, useHealthCheck } from '@workspace/api-client-react';

const navItems = [
  { href: '/', label: 'Visão geral', icon: Activity },
  { href: '/consultas', label: 'Consultas', icon: CalendarDays },
  { href: '/pacientes', label: 'Pacientes', icon: UsersRound },
  { href: '/relatorios', label: 'Relatórios', icon: FileBarChart },
  { href: '/definicoes', label: 'Definições', icon: Settings2 },
];

export function HospitalShell({ children }: { children: ReactNode }) {
  const [location] = useLocation();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [notice, setNotice] = useState('');
  const health = useHealthCheck({ query: { queryKey: getHealthCheckQueryKey(), staleTime: 30_000 } });
  const today = new Intl.DateTimeFormat('pt-PT', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date());
  const sidebar = <aside className="flex h-full w-[246px] shrink-0 flex-col bg-sidebar text-sidebar-foreground">
    <div className="flex h-[76px] items-center border-b border-sidebar-border px-5"><div className="mr-3 flex size-9 items-center justify-center rounded-[11px] bg-sidebar-primary text-sidebar-primary-foreground"><HeartPulse size={20} strokeWidth={2.5} /></div><div><p className="text-[13px] font-bold tracking-[-0.02em]">Hospital de Malanje</p><p className="mt-0.5 font-mono-ui text-[9px] uppercase tracking-[0.13em] text-sidebar-foreground/55">Central de consultas</p></div></div>
    <div className="px-4 pt-6"><p className="mb-2 px-3 font-mono-ui text-[9px] uppercase tracking-[0.18em] text-sidebar-foreground/45">Operação</p>{navItems.slice(0, 3).map(item => { const active = item.href === '/' ? location === '/' : location.startsWith(item.href); const Icon = item.icon; return <Link key={item.href} href={item.href} data-testid={`link-nav-${item.label.toLowerCase()}`} onClick={() => setMobileOpen(false)} className={`group mb-1 flex items-center gap-3 rounded-[9px] px-3 py-2.5 text-[13px] font-medium transition ${active ? 'bg-sidebar-primary text-sidebar-primary-foreground' : 'text-sidebar-foreground/72 hover:bg-sidebar-foreground/8 hover:text-sidebar-foreground'}`}><Icon size={17} strokeWidth={active ? 2.3 : 1.8} /><span>{item.label}</span>{active && <ChevronRight size={14} className="ml-auto opacity-60" />}</Link>; })}</div>
    <div className="px-4 pt-7"><p className="mb-2 px-3 font-mono-ui text-[9px] uppercase tracking-[0.18em] text-sidebar-foreground/45">Análise e acesso</p>{navItems.slice(3).map(item => { const active = location.startsWith(item.href); const Icon = item.icon; return <Link key={item.href} href={item.href} data-testid={`link-nav-${item.label.toLowerCase()}`} onClick={() => setMobileOpen(false)} className={`group mb-1 flex items-center gap-3 rounded-[9px] px-3 py-2.5 text-[13px] font-medium transition ${active ? 'bg-sidebar-primary text-sidebar-primary-foreground' : 'text-sidebar-foreground/72 hover:bg-sidebar-foreground/8 hover:text-sidebar-foreground'}`}><Icon size={17} strokeWidth={active ? 2.3 : 1.8} /><span>{item.label}</span>{active && <ChevronRight size={14} className="ml-auto opacity-60" />}</Link>; })}</div>
    <div className="mt-auto p-4"><div className="rounded-[12px] border border-sidebar-border bg-sidebar-foreground/5 p-3"><div className="flex items-center gap-2"><div className={`size-2 rounded-full ${health.isError ? 'bg-[#e88774]' : 'bg-sidebar-primary'}`} /><span className="text-xs font-semibold">{health.isError ? 'Verificar ligação' : 'Sistema operacional'}</span></div><p className="mt-1.5 text-[11px] leading-4 text-sidebar-foreground/55">Dados sincronizados para a equipa de hoje.</p></div><div className="mt-4 flex items-center gap-2.5 border-t border-sidebar-border pt-4"><div className="flex size-8 items-center justify-center rounded-full bg-[#d88968] text-[11px] font-bold text-[#194b48]">AM</div><div className="min-w-0"><p className="truncate text-xs font-semibold">Ana Manuel</p><p className="truncate text-[10px] text-sidebar-foreground/50">Coordenação</p></div><button data-testid="button-sidebar-menu" onClick={() => setNotice('Perfil activo: Ana Manuel · Coordenação')} aria-label="Menu do utilizador" className="ml-auto rounded p-1 text-sidebar-foreground/60 hover:bg-sidebar-foreground/10"><Command size={14} /></button></div></div>
  </aside>;
  return <div className="app-noise flex min-h-[100dvh] bg-background"><div className={`fixed inset-y-0 left-0 z-40 transition-transform md:relative md:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>{sidebar}</div>{mobileOpen && <button data-testid="button-close-mobile-nav" aria-label="Fechar navegação" onClick={() => setMobileOpen(false)} className="fixed inset-0 z-30 bg-[#123e3a]/35 md:hidden"><X className="absolute right-5 top-5 text-card" /></button>}<main className="min-w-0 flex-1"><header className="flex h-[76px] items-center justify-between border-b border-border bg-card/75 px-4 backdrop-blur-sm sm:px-7"><div className="flex items-center gap-3"><button data-testid="button-open-mobile-nav" aria-label="Abrir navegação" onClick={() => setMobileOpen(true)} className="rounded-lg p-2 text-muted-foreground hover:bg-muted md:hidden"><Menu size={20} /></button><div className="hidden items-center gap-2 text-xs text-muted-foreground sm:flex"><Wifi size={14} className="text-primary" /><span>Malanje · {today}</span></div></div><div className="flex items-center gap-3"><div className="hidden items-center gap-2 rounded-full border border-border bg-background px-3 py-1.5 sm:flex"><span className="size-1.5 rounded-full bg-[#2c9b81]" /><span className="font-mono-ui text-[10px] text-muted-foreground">Actualizado agora</span></div><button data-testid="button-notifications" onClick={() => setNotice('Não há novas notificações operacionais.')} aria-label="Notificações" className="relative rounded-lg p-2 text-muted-foreground transition hover:bg-muted hover:text-foreground"><ClipboardList size={18} /><span className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-accent" /></button><div className="flex size-8 items-center justify-center rounded-full bg-primary text-[11px] font-bold text-primary-foreground">AM</div></div></header>{notice && <div data-testid="status-shell-notice" className="mx-4 mt-3 flex items-center justify-between rounded-lg border border-border bg-card px-3 py-2 text-xs text-muted-foreground shadow-soft sm:mx-7"><span>{notice}</span><button data-testid="button-dismiss-shell-notice" onClick={() => setNotice('')} aria-label="Fechar aviso"><X size={14} /></button></div>}<div className="mx-auto max-w-[1440px] p-4 sm:p-7">{children}</div></main></div>;
}