# Require dependencies to be published for at least one day before installation.
# Replit packages are excluded because they are published and maintained by Replit.
minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@replit/*'

packages:
  - artifacts/*

catalog:
  tailwindcss: ^4.1.14

autoInstallPeers: false