import { BarChart3, CalendarDays, CheckCircle2, Clock3, Download, TrendingUp, UsersRound } from 'lucide-react';
import { useMemo, useState } from 'react';
import { getGetDashboardSummaryQueryKey, getListAppointmentsQueryKey, useGetDashboardSummary, useListAppointments } from '@workspace/api-client-react';
import { Button, EmptyState, ErrorState, LoadingRows, MetricCard, PageHeading, SelectField, StatusBadge } from '@/components/hospital-ui';

export default function Reports() {
  const [period, setPeriod] = useState('today');
  const summaryQuery = useGetDashboardSummary({ query: { queryKey: getGetDashboardSummaryQueryKey(), staleTime: 30_000 } });
  const appointmentsQuery = useListAppointments({}, { query: { queryKey: getListAppointmentsQueryKey({}), staleTime: 30_000 } });
  const summary = summaryQuery.data;
  const appointments = appointmentsQuery.data ?? [];
  const totals = useMemo(() => appointments.reduce((acc, item) => { acc[item.status] = (acc[item.status] ?? 0) + 1; return acc; }, {} as Record<string, number>), [appointments]);
  const maxDept = Math.max(...(summary?.departments ?? []).map(dept => dept.total), 1);
  return <div className="animate-enter">
    <PageHeading eyebrow="Leitura operacional" title="Relatórios" description="Indicadores simples para orientar a equipa e melhorar o atendimento."><SelectField testId="select-report-period" value={period} onChange={setPeriod} className="min-w-[155px]"><option value="today">Hoje</option><option value="week">Esta semana</option><option value="month">Este mês</option></SelectField><Button variant="outline" testId="button-export-report" onClick={() => window.print()}><Download size={15} /> Exportar</Button></PageHeading>
    {summaryQuery.isLoading || appointmentsQuery.isLoading ? <LoadingRows rows={6} /> : summaryQuery.isError || appointmentsQuery.isError ? <div className="rounded-[14px] border border-border bg-card"><ErrorState onRetry={() => { summaryQuery.refetch(); appointmentsQuery.refetch(); }} /></div> : summary ? <>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Volume de consultas" value={summary.totalAppointments} detail="no período seleccionado" icon={BarChart3} tone="teal" /><MetricCard label="Taxa de conclusão" value={`${summary.totalAppointments ? Math.round(summary.completedAppointments / summary.totalAppointments * 100) : 0}%`} detail={`${summary.completedAppointments} consultas concluídas`} icon={CheckCircle2} tone="blue" /><MetricCard label="Tempo médio de espera" value={`${summary.averageWaitMinutes ?? 0} min`} detail="até ao atendimento" icon={Clock3} tone="amber" /><MetricCard label="Pacientes na fila" value={summary.waitingPatients} detail="aguardam neste momento" icon={UsersRound} tone="coral" /></div>
      <div className="mt-5 grid gap-5 lg:grid-cols-[1.25fr_0.75fr]"><div className="rounded-[14px] border border-border bg-card shadow-soft"><div className="border-b border-border px-5 py-4"><h2 className="text-sm font-bold">Ritmo por departamento</h2><p className="mt-0.5 text-xs text-muted-foreground">Consultas agendadas e percurso concluído</p></div><div className="space-y-5 p-5">{summary.departments.length ? summary.departments.map(dept => <div key={dept.departmentId}><div className="mb-2 flex items-center justify-between text-xs"><span className="font-semibold">{dept.departmentName}</span><span className="font-mono-ui text-[10px] text-muted-foreground">{dept.total} total</span></div><div className="flex h-8 gap-1"><div title={`${dept.completed} concluídas`} className="flex items-center justify-end rounded-l-md bg-primary px-2 text-[10px] font-bold text-primary-foreground transition-all" style={{ width: `${Math.max((dept.completed / maxDept) * 100, dept.completed ? 8 : 0)}%` }}>{dept.completed || ''}</div><div title={`${dept.waiting} em espera`} className="flex items-center rounded-r-md bg-[#f5d9b5] px-2 text-[10px] font-bold text-[#805326]" style={{ width: `${Math.max((dept.waiting / maxDept) * 100, dept.waiting ? 8 : 0)}%` }}>{dept.waiting || ''}</div></div></div>) : <EmptyState title="Sem dados por departamento" description="Quando existirem consultas, verá aqui o ritmo de cada área." icon={BarChart3} />}</div></div><div className="rounded-[14px] border border-border bg-card shadow-soft"><div className="border-b border-border px-5 py-4"><h2 className="text-sm font-bold">Estados da agenda</h2><p className="mt-0.5 text-xs text-muted-foreground">Distribuição no período</p></div><div className="space-y-3 p-5">{Object.entries({ scheduled: 'Agendadas', confirmed: 'Confirmadas', waiting: 'Em espera', in_progress: 'Em atendimento', completed: 'Concluídas', cancelled: 'Canceladas', no_show: 'Não compareceu' }).map(([key, label]) => <div key={key} className="flex items-center justify-between"><StatusBadge status={key} /><span className="font-mono-ui text-sm font-bold">{totals[key] ?? 0}</span></div>)}<div className="mt-5 flex items-center gap-2 border-t border-border pt-4 text-xs text-muted-foreground"><TrendingUp size={15} className="text-primary" /> Dados baseados na agenda disponível</div></div></div></div>
      <div className="mt-5 rounded-[14px] border border-border bg-card shadow-soft"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="text-sm font-bold">Consultas no período</h2><p className="mt-0.5 text-xs text-muted-foreground">Registos usados neste resumo</p></div><CalendarDays size={17} className="text-primary" /></div>{appointments.length ? <div className="grid gap-0 divide-y divide-border md:grid-cols-2">{appointments.slice(0, 8).map(item => <div key={item.id} className="flex items-center gap-3 px-5 py-3"><div className="font-mono-ui text-xs font-bold text-primary">{item.time.slice(0, 5)}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{item.patientName}</p><p className="truncate text-[10px] text-muted-foreground">{item.departmentName}</p></div><StatusBadge status={item.status} /></div>)}</div> : <EmptyState title="Sem consultas no período" description="Não existem registos para compor este relatório." icon={CalendarDays} />}</div>
    </> : null}
  </div>;
}