import { BellRing, Check, ChevronRight, KeyRound, LockKeyhole, Save, ShieldCheck, UserRound, UsersRound } from 'lucide-react';
import { useState } from 'react';
import { Button, FormField, PageHeading } from '@/components/hospital-ui';

const inputClass = 'h-10 w-full rounded-[9px] border border-input bg-card px-3 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15';
const roles = [['Recepção', 'Agenda e registo de pacientes', 'RE'], ['Enfermagem', 'Fila e estados de atendimento', 'EN'], ['Coordenação', 'Visão completa e relatórios', 'CO'], ['Médicos', 'Agenda e percurso próprio', 'MD']];

export default function Settings() {
  const [saved, setSaved] = useState(false);
  const [selectedRole, setSelectedRole] = useState('Coordenação');
  const [autoRefresh, setAutoRefresh] = useState(true);
  const [queueAlerts, setQueueAlerts] = useState(true);
  const [notice, setNotice] = useState('');
  const save = () => { setSaved(true); window.setTimeout(() => setSaved(false), 2400); };
  return <div className="animate-enter">
    <PageHeading eyebrow="Administração local" title="Definições" description="Ajuste a central de consultas ao modo de trabalho da sua equipa."><Button testId="button-save-settings" onClick={save}>{saved ? <Check size={16} /> : <Save size={16} />}{saved ? 'Alterações guardadas' : 'Guardar alterações'}</Button></PageHeading>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_310px]">
      <div className="space-y-5">{notice && <div data-testid="status-settings-notice" className="flex items-center justify-between rounded-lg bg-secondary px-4 py-3 text-xs text-primary"><span>{notice}</span><button data-testid="button-dismiss-settings-notice" onClick={() => setNotice('')} aria-label="Fechar aviso"><Check size={15} /></button></div>}
        <section className="rounded-[14px] border border-border bg-card shadow-soft"><div className="flex items-center gap-3 border-b border-border px-5 py-4"><div className="flex size-9 items-center justify-center rounded-[10px] bg-secondary text-primary"><BellRing size={17} /></div><div><h2 className="text-sm font-bold">Ritmo da operação</h2><p className="mt-0.5 text-xs text-muted-foreground">Como a informação chega à equipa</p></div></div><div className="divide-y divide-border"><label className="flex cursor-pointer items-center justify-between gap-4 px-5 py-4"><div><p className="text-sm font-semibold">Actualização automática</p><p className="mt-1 text-xs text-muted-foreground">Actualizar a agenda a cada 30 segundos</p></div><input data-testid="switch-auto-refresh" type="checkbox" checked={autoRefresh} onChange={e => setAutoRefresh(e.target.checked)} className="peer sr-only" /><span className={`relative h-6 w-11 rounded-full transition ${autoRefresh ? 'bg-primary' : 'bg-muted'}`}><span className={`absolute top-1 size-4 rounded-full bg-card shadow transition ${autoRefresh ? 'left-6' : 'left-1'}`} /></span></label><label className="flex cursor-pointer items-center justify-between gap-4 px-5 py-4"><div><p className="text-sm font-semibold">Alertas de fila</p><p className="mt-1 text-xs text-muted-foreground">Avisar quando a espera ultrapassa 30 minutos</p></div><input data-testid="switch-queue-alerts" type="checkbox" checked={queueAlerts} onChange={e => setQueueAlerts(e.target.checked)} className="peer sr-only" /><span className={`relative h-6 w-11 rounded-full transition ${queueAlerts ? 'bg-primary' : 'bg-muted'}`}><span className={`absolute top-1 size-4 rounded-full bg-card shadow transition ${queueAlerts ? 'left-6' : 'left-1'}`} /></span></label></div></section>
        <section className="rounded-[14px] border border-border bg-card shadow-soft"><div className="flex items-center gap-3 border-b border-border px-5 py-4"><div className="flex size-9 items-center justify-center rounded-[10px] bg-secondary text-primary"><UserRound size={17} /></div><div><h2 className="text-sm font-bold">Perfil de trabalho</h2><p className="mt-0.5 text-xs text-muted-foreground">Identidade apresentada nas actividades</p></div></div><div className="grid gap-4 p-5 sm:grid-cols-2"><FormField label="Nome"><input data-testid="input-settings-name" defaultValue="Ana Manuel" className={inputClass} /></FormField><FormField label="Função"><input data-testid="input-settings-role" defaultValue="Coordenação" className={inputClass} /></FormField><FormField label="Unidade"><input data-testid="input-settings-unit" defaultValue="Hospital de Malanje" className={inputClass} /></FormField><FormField label="Contacto"><input data-testid="input-settings-contact" defaultValue="+244 923 000 144" className={inputClass} /></FormField></div></section>
        <section className="rounded-[14px] border border-border bg-card shadow-soft"><div className="flex items-center gap-3 border-b border-border px-5 py-4"><div className="flex size-9 items-center justify-center rounded-[10px] bg-secondary text-primary"><ShieldCheck size={17} /></div><div><h2 className="text-sm font-bold">Perfis de acesso</h2><p className="mt-0.5 text-xs text-muted-foreground">Papéis configurados para esta central · activo: {selectedRole}</p></div></div><div className="divide-y divide-border">{roles.map(([role, detail, initials]) => <button onClick={() => setSelectedRole(role)} data-testid={`button-role-${role.toLowerCase()}`} key={role} className={`flex w-full items-center gap-3 px-5 py-3 text-left transition hover:bg-[#fbf8f2] ${selectedRole === role ? 'bg-secondary/60' : ''}`}><span className="flex size-8 items-center justify-center rounded-full bg-secondary font-mono-ui text-[10px] font-bold text-primary">{initials}</span><span className="flex-1"><span className="block text-xs font-bold">{role}</span><span className="mt-0.5 block text-[11px] text-muted-foreground">{detail}</span></span>{selectedRole === role ? <Check size={15} className="text-primary" /> : <ChevronRight size={15} className="text-muted-foreground" />}</button>)}</div></section>
      </div>
      <aside className="space-y-4"><div className="rounded-[14px] bg-primary p-5 text-primary-foreground"><KeyRound size={19} className="mb-7 text-[#f4bd80]" /><p className="font-mono-ui text-[10px] uppercase tracking-[0.15em] text-primary-foreground/55">Acesso seguro</p><h2 className="mt-2 text-lg font-bold leading-tight">A central é só da equipa.</h2><p className="mt-2 text-xs leading-5 text-primary-foreground/70">As permissões mantêm cada pessoa focada no que precisa de fazer, sem ruído.</p><button data-testid="button-change-password" onClick={() => setNotice('A alteração de palavra-passe deve ser feita com a administração do hospital.')} className="mt-5 flex h-9 w-full items-center justify-center gap-2 rounded-lg bg-primary-foreground/10 text-xs font-semibold transition hover:bg-primary-foreground/20"><LockKeyhole size={14} /> Alterar palavra-passe</button></div><div className="rounded-[14px] border border-border bg-card p-5 shadow-soft"><div className="flex items-center gap-2 text-primary"><UsersRound size={17} /><h3 className="text-sm font-bold">Ajuda para a equipa</h3></div><p className="mt-2 text-xs leading-5 text-muted-foreground">Se precisar de adicionar uma pessoa ou ajustar um perfil, fale com a coordenação do hospital.</p><p className="mt-4 flex items-center gap-2 text-[11px] font-semibold text-primary"><span className="size-1.5 rounded-full bg-primary" /> Dados protegidos localmente</p></div></aside>
    </div>
  </div>;
}